config/routes.rb
Rails.application.routes.draw do
   
  root 'users#index'
  
  get 'map' => 'users#map', as: :map

  get '/search/map' => 'searches#map', as: :search_map

  get 'teachers' => 'users#teachers'
  put 'teachers/:id' => 'users#update', as: :teacher
  patch 'teachers/:id' => 'users#update'

  get 'students' => 'users#students'
  put 'students/:id' => 'users#update', as: :student
  patch 'students/:id' => 'users#update'
  
  get 'venues' => 'users#venues'
  put 'venues/:id' => 'users#update', as: :venue
  patch 'venues/:id' => 'users#update'

  get 'show/:id' => 'users#show'
  get 'reviews_by/:id' =>'reviews#show_by', as: :reviews_by
  
  get 'searches' =>'searches#new'
  get 'searches/update_regions', to: 'searches#update_regions', :as => 'search_regions'
  get 'searches/update_cities', to: 'searches#update_cities', :as => 'search_cities'
  get 'users/update_regions', to: 'users#update_regions', :as => 'user_regions'
  get 'users/update_cities', to: 'users#update_cities', :as => 'user_cities'
  
  post 'search' => 'searches#create', as: :search_users

  resources :reviews
  resources :users, only: [:create, :index, :show, :edit, :update, :new, :destroy]
  resources :categories, only: [:create, :index, :show, :edit, :update, :new, :destroy]
  resources :searches, only: [:create, :new, :update]

  post 'reviews' => 'reviews#create'

 

  post   "/login",  to: "login#create"
  delete "/logout", to: "login#destroy"

end

app/models/user.rb
class User < ActiveRecord::Base

	mount_uploader :picture, UserPictureUploader
	TYPES = ["Teacher","Venue","Student"]
	has_secure_password

	has_many :reviews
	has_many :reviews_by, class_name: "Review", foreign_key: "author_id"
	has_many :reviews_to, class_name: "Review", foreign_key: "reviewed_id"
	has_many :courses, class_name: "Course", foreign_key: "courses_id"
	belongs_to :city
	belongs_to :region
	belongs_to :country

	validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i } 
	validates_length_of :short_description, :maximum => 80
	has_and_belongs_to_many :categories

	geocoded_by :full_street_address   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates
	
	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode  # auto-fetch address

	def full_street_address
		city = (self.city) ? self.city.name : ""
		region = (self.region) ? self.region.name : ""
		country = (self.country) ? self.country.name : ""
  	[address, town, city, region, country].compact.join(', ')
	end

	scope :located, -> { where.not(latitude: nil).where.not(longitude: nil) }
	
	def average_rating
		if self.reviews_to.count > 0
  	(self.reviews_to.sum(:rating).to_f / self.reviews_to.size.to_f).round(2)
	  else
	  	0
	  end
	end

	def url
		("users/"+ self.id.to_s)
	end

	def full_name
		self.name + " " + self.last_name
	end

	def accordion
		"accordion" + self.id.to_s
	end

	def haccordion
		"#accordion" + self.id.to_s
	end

	def av_stars
		"av_stars" + self.id.to_s
	end

	def admin
		self.email == "jordi@jordi.com"
	end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	rescue_from Pundit::NotAuthorizedError, with: :deny_access

  include Pundit

	before_action :load_user, only: [:edit, :update, :show, :destroy]

  before_action :load_geo_data, only: [:edit, :update, :new]

  def index
    # # variables for searching from users index
    # @countries  = Country.all
    # @regions = []
    # @cities = []
    # @search = Search.new
    @users = User.all
    #  @users = policy_scope(User)
  end

  def map
    @users = User.located
    render :json => @users
  end
  
  def teachers
    @users = Teacher.all
    render :index
  end

  def venues
    @users = Venue.all
    render :index
  end

  def students
    @users = Student.all
    render :index
  end

  def new
  	@user = User.new
  end

  def show
  end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_url
		else
 			render :new
		end
    rescue ActiveRecord::RecordNotUnique 
    @user.errors.add(:email, "There is already a user with this email")
    render :new
	end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "user updated successfully"
      redirect_to users_path(@user)
    else
      flash[:error]  = "Ops! We couldn't update the user, please review the errors"
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    redirect_to users_url
  end

  
  def update_regions
    # updates regions and cities based on country selected
    country = Country.find(params[:country_id])
    # map to name and id for use in our options_for_select
    @regions = country.regions.map{|r| [r.name, r.id]}.insert(0, "Select a region")
  end

  def update_cities
    # updates cities based on region selected
    region = Region.find(params[:region_id])
    @cities = region.cities.map{|c| [c.name, c.id]}.insert(0, "Select a city")
  end

  def full_street_address
    if params[:city_id] > 0 then city = City.find(params[:city_id]) end
    if params[:region_id] > 0 then region = Region.find(params[:region_id]) end
    if params[:country_id] > 0 then country = Country.find(params[:country_id]) end
    
    full_address = [address, :town, city.name, region.name, country.name].compact.join(', ')
    return full_address
  end
  
  private

  def deny_access
    render text: "Your are not authorized to perform this action", status: :unauthorized
  end

  def user_params
    if !params[:user].nil?
      @type_of_user = "user" 
  	  params.require(:user).permit(:name, :last_name, :password, :password_confirmation, :email, :address, :type, :town, :city_id, :region_id, :country_id, :description, :short_description, :website_url, :category_id, :picture, category_ids: []) 
         
    elsif !params[:teacher].nil?
      @type_of_user = "teacher"
      params.require(:teacher).permit(:name, :last_name, :password, :password_confirmation, :email, :address, :type, :town, :city_id, :region_id, :country_id, :description, :short_description, :website_url, :category_id, :picture, category_ids: [])
               
    elsif !params[:student].nil?
      @type_of_user = "student" 
      params.require(:student).permit(:name, :last_name, :password, :password_confirmation, :email, :address, :type, :town, :city_id, :region_id, :country_id, :description, :short_description, :website_url, :category_id, :picture, category_ids: []) 
         
    elsif !params[:venue].nil?
      
      @type_of_user = "venue" 
      params.require(:venue).permit(:name, :last_name, :password, :password_confirmation, :email, :address, :type, :town, :city_id, :region_id, :country_id, :description, :short_description, :website_url, :category_id, :picture, category_ids: []) 
       
    else 
      @type_of_user = "error"
      render text: "Incorrect type of user in params"
    end
  end

  private

  def load_user
    @user = User.find(params[:id])
#   authorize @user
  end

  def load_geo_data
    @countries = Country.all
    @regions = []
    @cities = []
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div><%= link_to image_tag("backarrow.png"), users_path, class: "backbutton" %></div>
<%= form_for @user do |u| %>
	<% if @user.errors.any? %>
		<% @user.errors.full_messages.each do |message| %>
			<%= message %>
		<% end %>
	<% end %>
	<div class="container-fluid">

		<div id="register-form">
			<div class="row-fluid">
				<div class="form-group">
					<%= u.label :name %>
					<%= u.text_field :name, class: "form-control register-input", placeholder: "First name" %>
				</div>
				<div class="form-group">
					<%= u.label :last_name %>
					<%= u.text_field :last_name, class: "form-control register-input", placeholder: "Last name" %>
				</div>
			</div>

	
		<div class="form-group">
			<%= u.label :address %>
			<%= u.text_field :address, class: "form-control register-input", placeholder: "Address" %>
		</div>
		<div class="form-group">
			<%= u.label :town %>
			<%= u.text_field :town, class: "form-control register-input", placeholder: "town" %>
		</div>
		<div class="form-group">
		    <%= u.collection_select :country_id,  @countries,  :id, :name, {:prompt  => "Select a Country"},{:id => 'u_countries_select'}  %>
	  	</div>
	  	<div class="form-group">
		    <%= u.collection_select :region_id, @regions, :id, :name, {:prompt  => "Select a region"},{:id => 'u_regions_select'} %>
		  <div class="form-group">
		    <%= u.collection_select :city_id, @cities, :id, :name, {:prompt  => "Select a City"},{:id => 'u_cities_select'} %>
		  </div>
		  <div class="form-group">
				<%= u.label :short_description %>
				<%= u.text_area :short_description, class: "form-control register-input", placeholder: "description", size: "80" %>
			</div>
			<div class="form-group">
				<%= u.label :description %>
				<%= u.text_area :description, class: "form-control register-input", placeholder: "description", size: "60x12" %>
			</div>
			<div class="form-group">
				<%= u.label :website_url %>
				<%= u.text_field :website_url, class: "form-control register-input", placeholder: "URL" %>
			</div>
			<div class="form-group">
				<%= u.label :email %>
				<%= u.text_field :email, class: "form-control register-input", placeholder: "Email" %>
			</div>
			<div class="form-group">
				<%= u.label :password %>
				<%= u.password_field :password, class: "form-control register-input", placeholder: "Password" %>
			</div>
			<div class="form-group">
				<%= u.label :repeat_password %>
				<%= u.password_field :password_confirmation, class: "form-control register-input", placeholder: "Password" %>
			</div>
			<label> Upload your Picture</label>
			<div class="field">
	    	<%= u.label :picture, id: "pictureLabel" %><br>
	    	<%= u.file_field :picture, class: "form-control register-input", placeholder: "Image url" %>
			</div>
			<div class="form-group">
				<%= u.label :type %>
				<%= u.select :type, User::TYPES.collect{ |t| [t]}%>
			</div>
			<div class="form-group">
				<%= u.label :category_ids, id: "categoryLabel" %>
				<%= u.collection_select :category_ids, Category.all, :id, :name, {}, { :multiple => true} %>
			</div>
			<div class="form-group">
				<%= u.submit "Ok", class: "btn btn-success"%>
			</div>

		</div>

	</div>
<% end %>

app/views/users/_input_review.html.erb
<% if current_user && ( current_user.id != @user.id) %>
  <% @review = Review.new %>
  <% @review.author_id = current_user.id %>
  <% @review.reviewed_id = @user.id %>
  <%= form_for @review, :html => {:class => "form-inline", :role => "form"} do |r| %>  
    <div class="hidden">
      <%= r.number_field :author_id %>
      <%= r.number_field :reviewed_id %>
    </div>
    <%= r.text_area :comment, class: "form-control", placeholder: "your comment" %>
    <%= r.number_field :rating, in: 0..5, class: "form-control", placeholder: "rate it", size: "5x1" %>
  <button class="btn btn-default btn-success">Add</button> 
  <% end %>

<% form_id = "user_#{@user.id}_rating" %>       
    <%= form_for @review, :html => {:id => form_id, :class => "star_rating_form"} do |f| %>
        <%= f.hidden_field :user_id, :value => @user.id %>      
        <%= f.hidden_field :rating, :id => form_id + "_stars" %>
    <% end %>
<% (1..5).each do |i| %>
    <li class="rating_star" id="<%= form_id %>_<%= i %>" data-stars="<%= i %>" data-form-id="<%= form_id %>"></li>
<% end %>


<% end %>

app/views/users/_logout_form.html.erb
<%= form_tag logout_path, method: :delete, :class => "navbar-form navbar-right", :role => "search" do %>
	<div class="form-group">
	You're logged as <%= current_user.name %>	
	</div>
  <%= submit_tag "Logout", :class => "logout btn btn-default" %>
<% end %>



   

app/views/users/_search_form.html.erb
<%= form_for @search, url: search_users_path, method: :post do |s| %>
  <div class="row">
  <div class="form-group col-md-1">
    <%= submit_tag  "Search", :class => "btn btn-success" %>
  </div>
  <div class="form-group col-md-1">
    <%= s.label :type, class: "help-block" %>
    <%= s.select :user_type, User::TYPES.collect{ |t| [t]}%>
  </div>
  <div class="form-group col-md-3">
    <%= s.label :country_id, class: "help-block" %>
    <%= s.collection_select :country_id,  @countries,  :id, :name, {:prompt => "Select a Country"}, {:id => 'u_countries_select'} if @countries %>
  </div>
  <div class="form-group col-md-1 form-vertical">
    <%= s.label :region_id, class: "help-block" %>
    <%= s.collection_select :region_id, @regions, :id, :name, {:prompt => "Select a Region"}, {:id => 'u_regions_select'} %>
  </div>
  <div class="form-group col-md-1" >
    <%= s.label :city_id, class: "help-block" %>
    <%= s.collection_select :city_id, @cities, :id, :name, {:prompt => "Select a City"}, {:id => 'u_cities_select'} %>
  </div>
  <div class="form-group col-md-2">
      <%= s.label :categories, class: "help-block" %>
      <%= s.collection_select :category_ids, Category.all, :id, :name, {}, { :multiple => true} %>
  </div>

  <div>
    <%= submit_tag  "Search", :class => "btn btn-success" %>
  </div>
  </div>
<% end %>

<script>
  $('#u_countries_select').change(function() {
    $.ajax({
      url: "<%= user_regions_path %>",
      type: "GET",
      data: {
        country_id : $('#u_countries_select').val()
      },
      dataType: "script"
    }).done(function (){ 
          $('#u_regions_select').change(function() {
            $.ajax({
              url: "<%= user_cities_path %>",
              type: "GET",
              data: {
                region_id : $('#u_regions_select').val()
              },
              dataType: "script"
            });
          });
        });
  });   
</script>

app/views/users/_show_categories.html.erb
<div class="row" >
    <p class = "h-subBox"><%= @user.type %>'s Categories</p>
</div>
<div class="actionBox">
<ul class="commentList">
<%if @user.categories.count > 0 %>
    <%  @user.categories.each do |c| %>
        <li>
            <div class="commentText">
                <p class="">
                <%= c.name %>
                </p> 
            </div>
        </li>
    <% end %>           
 <%else %>
    <li>
        <div class="commentText">
            <p class="">Still no categories</p> 
        </div>
    </li>
<% end %>
</ul>
</div>





 

app/views/users/_show_reviews.html.erb
<div class="row">
    <p class = "h-subBox">Reviews about <%= @user.name %></p>
</div>
    <div class="actionBox">

      <ul class="commentList">
        <% if @user.reviews_to.count > 0 %>
          <%  @user.reviews_to.each do |r| %>
            <li>
              <div class="commenterImage">
                <%= image_tag r.author.picture if r.author %>
              </div>
              <div class="commentText">
                  <p class=""><%= r.comment %></p> <span class="date sub-text">on <%=r.updated_at %> by <%= r.author.name if r.author %></span><span class="date sub-text">, rated with <%=r.rating %></span>
              </div>
          
            </li>
          <% end %>
          <% else %>
            <li>
              <div class="commentText">
                <p class=""> This user has still no reviews</p>
              </div>
            </li>
          <% end %>
      </ul>
    </div>

app/views/users/_show_reviews2.html.erb
<div class="reviewsBox">
  <div class="col-md-12">
    <div class="titleBox">
      <label>Reviews about <%= @user.name %></label>
      <button type="button" class="close" aria-hidden="true">&times;</button>
    </div>
    <div class="actionBox">
      <ul class="commentList">
        <% if @user.reviews_to.count > 0 %>
          <%  @user.reviews_to.each do |r| %>
            <li>
                <div class="commenterImage">
                  <%= image_tag r.author.picture %>
                </div>
                <div class="commentText">
                    <p class=""><%= r.comment %></p> <span class="date sub-text">on <%=r.updated_at %> by <%= r.author.name %></span>
                </div>
            </li>
          <% end %>
          <% else %>
            <li>
              <div class="commentText">
                <p class=""> This user has still no reviews</p>
              </div>
            </li>
          <% end %>
      </ul>
      <% if current_user && ( current_user.id != @user.id) %>
        <% @review = Review.new %>
        <% @review.author_id = current_user.id %>
        <% @review.reviewed_id = @user.id %>
        <%= form_for @review, :html => {:class => "form-inline", :role => "form"} do |r| %>  
          <div class="hidden">
            <%= r.number_field :author_id %>
            <%= r.number_field :reviewed_id %>
          </div>
          <%= r.text_area :comment, class: "form-control", placeholder: "your comment", size: "40x5" %>
          <%= r.number_field :rating, in: 0..5, class: "form-control", placeholder: "rate it", size: "5x1" %>

          <!-- <%= r.submit class: "btn btn-default"%>    -->
        <button class="btn btn-default">Add</button> 
        <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/users/_show_reviews_boots.html.erb
<%= form_for @review, remote: true do |r| %>
<div class="row" style="margin-top:40px;">
	<div class="col-md-12">
  	<div class="well well-sm">
      <div class="text-right">
          <a class="btn btn-success btn-green" href="#reviews-anchor" id="open-review-box">Leave a Review</a>
      </div> 
      <div class="row" id="post-review-box" style="display:none;">
        <div class="col-md-12">
          <form accept-charset="UTF-8" url="reviews" action="create" method="post">
            <div class="hidden">
              <%= r.number_field :author_id%>
              <%= r.number_field :reviewed_id%>
            </div>
<!--             <input id="ratings-hidden" name="rating" type="hidden"> --> 
            <div class="form-group hidden">
              <%= r.label :rating %>
              <%= r.number_field :rating, class: "form-control", placeholder: "Rating", id: "ratings-hidden", type: "hidden"%>
            </div>
            <div class="form-group">
              <%= r.label :review %>
              <%= r.text_area :comment, class: "form-control  animated", placeholder: "Comment", size: "50x5" %>
            </div>
           <!--  <textarea class="form-control animated" cols="50" id="new-review" name="comment" placeholder="Enter your review here..." rows="5"></textarea>
 -->
            <div class="text-right">
              <div class="stars starrr" data-rating="0"></div>
              <a class="btn btn-danger btn-sm" href="#" id="close-review-box" style="display:none; margin-right: 10px;">
              <span class="glyphicon glyphicon-remove"></span>Cancel</a>
              <button class="btn btn-success btn-lg" type="submit">Save</button>
            </div>
          </form>
        </div>
      </div>
      </div>      
	</div>
</div>
<% end %>

app/views/users/_user.html.erb
<td><%= image_tag user.picture, :class => "userImage"%></td>
				<td><%= user.name %></td>
				<td><%= user.last_name %></td>
				<td><%= user.email %></td>
				<td><%= user.address %></td>
				<td><%= user.city.name if user.city %></td>
				<td><%= user.region.name if user.region %></td>
				<td><%= user.country.name if user.country %></td>
				<td><%= user.latitude %></td>
				<td><%= user.longitude %></td>
				<td><%= user.website_url %></td>

app/views/users/edit.html.erb
<%= render 'form' %>

<script>
  $('#u_countries_select').change(function() {
    $.ajax({
      url: "<%= user_regions_path %>",
      type: "GET",
      data: {
        country_id : $('#u_countries_select').val()
      },
      dataType: "script"
    }).done(function (){ 
          $('#u_regions_select').change(function() {
            $.ajax({
              url: "<%= user_cities_path %>",
              type: "GET",
              data: {
                region_id : $('#u_regions_select').val()
              },
              dataType: "script"
            });
          });
        });
  });   
</script>

app/views/users/index.html.erb
<%if @users.length == 0 %>
	<h4> Nothing to show. No results </h4>
<%end%>
<% @users.each do |u| %>
	<% @user = u %>
	<div class="panel-group" id="accordion">
   	<div class="panel-heading">
      <div class="row">
          <div class="col-md-1 ">
						<%= link_to (image_tag u.picture, :class => "userImage"), u.url %>
					</div>
					<div class="col-md-11">
						<div class="row">	
        			<div class="col-md-8">												
							<table class="table no-margin-bottom">
								<tr>
										<th class="col-md-1"><%= image_tag u.country, src: "assets/blank.gif", class: "flag "+u.country.flag, alt: u.country.name if u.country %></th>
										<th class="col-md-3"><%= u.full_name %></th>
										
										<td class="col-md-2"><%= u.country.name if u.country %></td>
										<td class="col-md-2"><%= u.city.name if u.city %></td>					
										<td class="col-md-2"><%= u.categories.first.name if u.city %></td> 
										<th class="col-md-2">
											<% if current_user %>
												<%	if current_user.admin %>
												<%=	link_to "Edit", edit_user_path(u) %>
												<%= link_to "Delete", user_path(u), method: :delete, data: { confirm: 'Are you sure?' } %>
												<%end %>						
											<%end %>
										</th>

								</tr>
								<!-- </thead> -->
							</table>
						</div>
					
						<div class="col-md-2">
							<%= if @user.average_rating == 0 
										"Not rated"
									else 
										@user.average_rating
									end %>
						</div>
						<div class="col-md-2">
							<button type="button" class="btn btn-toogle" data-toggle="collapse" data-target= <%= @user.haccordion %> >
							</button>
						</div>
					<div class = "col-md-12">
						<p><%= @user.short_description%></p>
					</div>
				</div> <!-- end of col-11 -->
					
			</div>  <!-- end of row -->

		</div>
	</div>
	</div>

	<div id=<%= @user.accordion %> class="panel-collapse collapse ">
			<div class="col-md-12 panel-border">
				<div class="col-md-8">
						<div class="row">
							<div class="col-md-2 nopadding-right nopadding-left panel-border">
								<%= render '/users/show_categories' %>
							</div>
							<div class="col-md-10 nopadding-right">
							<div class="col-md-12 nopadding-right panel-border-white ">
								<%=render '/users/show_description' %>
							</div>
							<div class="col-md-12 nopadding-right panel-border">
								<%=render '/users/input_review' %>
							</div>
							</div>
						</div>
				</div>
				<!-- end of col-8 -->
		    <div class="col-md-4 nopadding-right panel-border">			
		   		<%= render '/users/show_reviews' %>
		   	</div>
			</div>
	</div> <!-- End of accordion -->
		
<% end %>
<div class="col-md-12">
			<%= render '/users/load_map'%>
</div>

app/views/users/new.html.erb
<%= render 'form' %>
 
<script>
  $('#u_countries_select').change(function() {
    $.ajax({
      url: "<%= user_regions_path %>",
      type: "GET",
      data: {
        country_id : $('#u_countries_select').val()
      },
      dataType: "script"
    }).done(function (){ 
          $('#u_regions_select').change(function() {
            $.ajax({
              url: "<%= user_cities_path %>",
              type: "GET",
              data: {
                region_id : $('#u_regions_select').val()
              },
              dataType: "script"
            });
          });
        });
  });   
</script>

app/views/users/show.html.erb
<div class="panel-body">
	<table class="table table_stripted">
		<thead class = "panel-heading">
			<th><%= @user.type %></th>
			<th>First name</th>
			<th>Last name</th>
			<th>Email</th>
			<th>Address</th>
			<th>City</th>
			<th>Region</th>
			<th>Country</th>
			<th>Latitude</th>
			<th>Longitude</th>
			<th>Website</th>
		</thead>
		<tbody>
			<tr>
				<td><%= image_tag @user.picture, :class => "userImage"%></td>
				<td><%= @user.name %></td>
				<td><%= @user.last_name %></td>
				<td><%= @user.email %></td>
				<td><%= @user.address %></td>
				<td><%= @user.city.name if @user.city %></td>
				<td><%= @user.region.name if @user.region %></td>
				<td><%= @user.country.name if @user.country %></td>
				<td><%= @user.latitude %></td>
				<td><%= @user.longitude %></td>
				<td><%= @user.website_url %></td>
				<% if admin %>
				<td>
					<%= link_to "Edit", edit_user_path(u) %>
					<%= link_to "Delete", user_path(u), method: :delete, data: { confirm: 'Are you sure?' } %>
					</td>	
				<% end %>		
			</tr>
		</tbody>
	</table>

	<div class="panel-border-white">
		<%= @user.short_description %>
	</div>
	<div class="panel-border">
		<%= render '/users/show_description' %>
	</div>
	<div class= "col-md-12 panel-border-white">
		<div class= "col-md-6">
			<%= render '/users/show_reviews' %>
		</div>
		<div class= "col-md-6">
			<%= render '/users/show_reviews_by' %>
		</div>
	</div>
	<%= link_to "Back", users_path %>
</div>

app/views/users/update_cities.js.erb
$('#u_cities_select').html("<%= escape_javascript(options_for_select(@cities)) %>");