config/routes.rb
Rails.application.routes.draw do
   
  root 'users#index'
  
  get 'map' => 'users#map', as: :map

  get '/search/map' => 'searches#map', as: :search_map

  get 'teachers' => 'users#teachers'
  put 'teachers/:id' => 'users#update', as: :teacher
  patch 'teachers/:id' => 'users#update'

  get 'students' => 'users#students'
  put 'students/:id' => 'users#update', as: :student
  patch 'students/:id' => 'users#update'
  
  get 'venues' => 'users#venues'
  put 'venues/:id' => 'users#update', as: :venue
  patch 'venues/:id' => 'users#update'

  get 'show/:id' => 'users#show'
  get 'reviews_by/:id' =>'reviews#show_by', as: :reviews_by
  
  get 'searches' =>'searches#new'
  get 'searches/update_regions', to: 'searches#update_regions', :as => 'search_regions'
  get 'searches/update_cities', to: 'searches#update_cities', :as => 'search_cities'
  get 'users/update_regions', to: 'users#update_regions', :as => 'user_regions'
  get 'users/update_cities', to: 'users#update_cities', :as => 'user_cities'
  
  post 'search' => 'searches#create', as: :search_users

  resources :reviews
  resources :users, only: [:create, :index, :show, :edit, :update, :new, :destroy]
  resources :categories, only: [:create, :index, :show, :edit, :update, :new, :destroy]
  resources :searches, only: [:create, :new, :update]

  post 'reviews' => 'reviews#create'

 

  post   "/login",  to: "login#create"
  delete "/logout", to: "login#destroy"

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/cat_relation.rb
class CatRelation < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	validates_presence_of :user_id, :category_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories, :class_name => "Category", :foreign_key => "parent_id", :dependent => :destroy
  belongs_to :parent_category, :class_name => "Category", :foreign_key => "parent_id"
  has_many :courses
  has_and_belongs_to_many :users
  has_many :categories, through: :categories

  def parent_name
  	 if parent_category then parent_category.name else "" end
  end
  def <=> another
    if self.name < another.name
      -1
    elsif self.name < another.name
      1
    else
      0
    end
  end
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :region
 	belongs_to :country
 	has_many :users
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :regions
	has_many :cities
	has_many :users, class_name: "User", foreign_key: "user_id"
	def flag
		"flag-"+self.iso2.downcase
	end
end

app/models/course.rb
class Course < ActiveRecord::Base	
	belongs_to :category
	belongs_to :venue
	belongs_to :teacher
	has_many :students
	has_many :reviews
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/region.rb
class Region < ActiveRecord::Base
	belongs_to :country
	has_many :cities
 	has_many :users
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :author, class_name: "User", foreign_key: "author_id"
	belongs_to :reviewed, class_name: "User", foreign_key: "reviewed_id"
	belongs_to :course
	validates_presence_of :rating, :author_id
	validates :rating, :inclusion => 0..5
end

app/models/search.rb
class Search < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :categories
end

app/models/student.rb
class Student < User
end

app/models/teacher.rb
class Teacher < User
end

app/models/user.rb
class User < ActiveRecord::Base

	mount_uploader :picture, UserPictureUploader
	TYPES = ["Teacher","Venue","Student"]
	has_secure_password

	has_many :reviews
	has_many :reviews_by, class_name: "Review", foreign_key: "author_id"
	has_many :reviews_to, class_name: "Review", foreign_key: "reviewed_id"
	has_many :courses, class_name: "Course", foreign_key: "courses_id"
	belongs_to :city
	belongs_to :region
	belongs_to :country

	validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i } 
	validates_length_of :short_description, :maximum => 80
	has_and_belongs_to_many :categories

	geocoded_by :full_street_address   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates
	
	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode  # auto-fetch address

	def full_street_address
		city = (self.city) ? self.city.name : ""
		region = (self.region) ? self.region.name : ""
		country = (self.country) ? self.country.name : ""
  	[address, town, city, region, country].compact.join(', ')
	end

	scope :located, -> { where.not(latitude: nil).where.not(longitude: nil) }
	
	def average_rating
		if self.reviews_to.count > 0
  	(self.reviews_to.sum(:rating).to_f / self.reviews_to.size.to_f).round(2)
	  else
	  	0
	  end
	end

	def url
		("users/"+ self.id.to_s)
	end

	def full_name
		self.name + " " + self.last_name
	end

	def accordion
		"accordion" + self.id.to_s
	end

	def haccordion
		"#accordion" + self.id.to_s
	end

	def av_stars
		"av_stars" + self.id.to_s
	end

	def admin
		self.email == "jordi@jordi.com"
	end



end

app/models/venue.rb
class Venue < User
end

app/controllers/login_controller.rb
# http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html
class LoginController < ApplicationController
  def create
    user = User.where(email: params[:email]).first
    # Session engaged
    if user && user.authenticate(params[:password])
      flash[:success] = "Login sucessful! Welcome #{user.name}!"

      session[:current_user_id] = user.id
    else
      flash[:error] = "Login was not sucessful"
    end

    redirect_to user_path(user.id)
  end

  def destroy
    session[:current_user_id] = nil

    respond_to do |format|
      format.html { redirect_to users_path }
      format.js   { render js: "window.location.href='#{users_path}'" }
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @countries  = Country.all
    @regions = []
    @cities = []
    @search = Search.new
  end

  def create
    @search = Search.new(search_params)
    if @search.save
      search_users
    else
      flash[:alert] = "Search unsuccessful"
      @countries  = Country.all
      @regions = Region.where(id: @search.region_id)
      @cities = (@search.city_id > 0) ? City.where(id: @search.city_id) : []
      render 'new'
    end
  end

  def search_users
    if !@search.category_ids[0]
      @users = User.all.to_a
    else
      @users = []
    end
    @search.category_ids.each  do |category|
      cat = Category.find(category)
      if cat
        @users_in_cat = cat.users
        @users = (@users + @users_in_cat).uniq
      end
    end
    
    @users.keep_if { |u| u.type == @search.user_type }
    
    city_search = (@search.city_id.nil?) ? 0 : @search.city_id
    region_search = (@search.region_id.nil?) ? 0 : @search.region_id
    country_search = (@search.country_id.nil?) ? 0 : @search.country_id
    
    if city_search > 0 
        @users.keep_if { |u| u.city_id == city_search }
    elsif region_search > 0    
          @users.keep_if { |u| u.region_id == region_search }
        elsif country_search > 0   
           @users.keep_if { |u| u.country_id == country_search }
    end
    render '/users/index'
  end

  #def map
  #  @users = @users.located.first
  #  @users.to_json
  #end

  def update_regions
    # updates regions and cities based on country selected
    country = Country.find(params[:country_id])
    # map to name and id for use in our options_for_select
    @regions = country.regions.map{|r| [r.name, r.id]}.insert(0, "Select a region")
  end

  def update_cities
    # updates cities based on region selected
    region = Region.find(params[:region_id])
    @cities = region.cities.map{|c| [c.name, c.id]}.insert(0, "Select a city")
    # respond_to do |format|
    #   format.html { redirect_to searches_url }
    #   format.js
    # end
  end

  private
  def search_params
    params.require(:search).permit(:user_type, :country_id, :region_id, :city_id, :search_string, :tags, category_ids:[])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/searches/_form.html.erb
<%= form_for @search, url: search_users_path, method: :post do |s| %>
  <div class="row">
  <div class="form-group col-md-1">
  </div>
  <div class="form-group col-md-1">
    <%= s.label :type, class: "help-block" %>
    <%= s.select :user_type, User::TYPES.collect{ |t| [t]}%>
  </div>
  <div class="form-group col-md-3">
    <%= s.label :country_id, class: "help-block" %>
    <%= s.collection_select :country_id,  @countries,  :id, :name, {:prompt => "Select a Country"}, {:id => 'countries_select'} if @countries %>
  </div>
  <div class="form-group col-md-1 form-vertical">
    <%= s.label :region_id, class: "help-block" %>
    <%= s.collection_select :region_id, @regions, :id, :name, {:prompt => "Select a Region"}, {:id => 'regions_select'} %>
  </div>
  <div class="form-group col-md-1" >
    <%= s.label :city_id, class: "help-block" %>
    <%= s.collection_select :city_id, @cities, :id, :name, {:prompt => "Select a City"}, {:id => 'cities_select'} %>
  </div>
  <div class="form-group col-md-2">
      <%= s.label :categories, class: "help-block" %>
      <%= s.collection_select :category_ids, Category.all, :id, :name, {}, { :multiple => true} %>
  </div>

  <div>
    <%= submit_tag  "Search", :class => "btn btn-success" %>
  </div>
  </div>
<% end %>

app/views/searches/_new.html.erb
<%= render 'searches/form' %>
 
<script>
    $('#countries_select').change(function() {
      $.ajax({
        url: "<%= search_regions_path %>",
        type: "GET",
        data: {
          country_id : $('#countries_select').val()
        },
        dataType: "script"
      }).done(function (){ 
            $('#regions_select').change(function() {
              $.ajax({
                url: "<%= search_cities_path %>",
                type: "GET",
                data: {
                  region_id : $('#regions_select').val()
                },
                dataType: "script"
              });
            });
          });
    });   
</script>

app/views/searches/index.html.erb
<%= render 'form' %>
 
<script>
    $('#countries_select').change(function() {
      $.ajax({
        url: "<%= update_regions_path %>",
        type: "GET",
        data: {
          country_id : $('#countries_select').val()
        },
        dataType: "script"
      }).done(function (){ 
            $('#regions_select').change(function() {
              $.ajax({
                url: "<%= update_cities_path %>",
                type: "GET",
                data: {
                  region_id : $('#regions_select').val()
                },
                dataType: "script"
              });
            });
          });
    });   
</script>

app/views/searches/new.html.erb
<%= render 'form' %>
 
<script>
    $('#countries_select').change(function() {
      $.ajax({
        url: "<%= search_regions_path %>",
        type: "GET",
        data: {
          country_id : $('#countries_select').val()
        },
        dataType: "script"
      }).done(function (){ 
            $('#regions_select').change(function() {
              $.ajax({
                url: "<%= search_cities_path %>",
                type: "GET",
                data: {
                  region_id : $('#regions_select').val()
                },
                dataType: "script"
              });
            });
          });
    });   
</script>

app/views/searches/update_cities.js.erb
$('#cities_select').html("<%= escape_javascript(options_for_select(@cities)) %>");

app/views/searches/update_regions.js.erb
$('#regions_select').html("<%= escape_javascript(options_for_select(@regions)) %>");