config/routes.rb
Rails.application.routes.draw do
   
  root 'users#index'
  
  get 'map' => 'users#map', as: :map

  get '/search/map' => 'searches#map', as: :search_map

  get 'teachers' => 'users#teachers'
  put 'teachers/:id' => 'users#update', as: :teacher
  patch 'teachers/:id' => 'users#update'

  get 'students' => 'users#students'
  put 'students/:id' => 'users#update', as: :student
  patch 'students/:id' => 'users#update'
  
  get 'venues' => 'users#venues'
  put 'venues/:id' => 'users#update', as: :venue
  patch 'venues/:id' => 'users#update'

  get 'show/:id' => 'users#show'
  get 'reviews_by/:id' =>'reviews#show_by', as: :reviews_by
  
  get 'searches' =>'searches#new'
  get 'searches/update_regions', to: 'searches#update_regions', :as => 'search_regions'
  get 'searches/update_cities', to: 'searches#update_cities', :as => 'search_cities'
  get 'users/update_regions', to: 'users#update_regions', :as => 'user_regions'
  get 'users/update_cities', to: 'users#update_cities', :as => 'user_cities'
  
  post 'search' => 'searches#create', as: :search_users

  resources :reviews
  resources :users, only: [:create, :index, :show, :edit, :update, :new, :destroy]
  resources :categories, only: [:create, :index, :show, :edit, :update, :new, :destroy]
  resources :searches, only: [:create, :new, :update]

  post 'reviews' => 'reviews#create'

 

  post   "/login",  to: "login#create"
  delete "/logout", to: "login#destroy"

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/cat_relation.rb
class CatRelation < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	validates_presence_of :user_id, :category_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories, :class_name => "Category", :foreign_key => "parent_id", :dependent => :destroy
  belongs_to :parent_category, :class_name => "Category", :foreign_key => "parent_id"
  has_many :courses
  has_and_belongs_to_many :users
  has_many :categories, through: :categories

  def parent_name
  	 if parent_category then parent_category.name else "" end
  end
  def <=> another
    if self.name < another.name
      -1
    elsif self.name < another.name
      1
    else
      0
    end
  end
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :region
 	belongs_to :country
 	has_many :users
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :regions
	has_many :cities
	has_many :users, class_name: "User", foreign_key: "user_id"
	def flag
		"flag-"+self.iso2.downcase
	end
end

app/models/course.rb
class Course < ActiveRecord::Base	
	belongs_to :category
	belongs_to :venue
	belongs_to :teacher
	has_many :students
	has_many :reviews
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/region.rb
class Region < ActiveRecord::Base
	belongs_to :country
	has_many :cities
 	has_many :users
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :author, class_name: "User", foreign_key: "author_id"
	belongs_to :reviewed, class_name: "User", foreign_key: "reviewed_id"
	belongs_to :course
	validates_presence_of :rating, :author_id
	validates :rating, :inclusion => 0..5
end

app/models/search.rb
class Search < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :categories
end

app/models/student.rb
class Student < User
end

app/models/teacher.rb
class Teacher < User
end

app/models/user.rb
class User < ActiveRecord::Base

	mount_uploader :picture, UserPictureUploader
	TYPES = ["Teacher","Venue","Student"]
	has_secure_password

	has_many :reviews
	has_many :reviews_by, class_name: "Review", foreign_key: "author_id"
	has_many :reviews_to, class_name: "Review", foreign_key: "reviewed_id"
	has_many :courses, class_name: "Course", foreign_key: "courses_id"
	belongs_to :city
	belongs_to :region
	belongs_to :country

	validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i } 
	validates_length_of :short_description, :maximum => 80
	has_and_belongs_to_many :categories

	geocoded_by :full_street_address   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates
	
	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode  # auto-fetch address

	def full_street_address
		city = (self.city) ? self.city.name : ""
		region = (self.region) ? self.region.name : ""
		country = (self.country) ? self.country.name : ""
  	[address, town, city, region, country].compact.join(', ')
	end

	scope :located, -> { where.not(latitude: nil).where.not(longitude: nil) }
	
	def average_rating
		if self.reviews_to.count > 0
  	(self.reviews_to.sum(:rating).to_f / self.reviews_to.size.to_f).round(2)
	  else
	  	0
	  end
	end

	def url
		("users/"+ self.id.to_s)
	end

	def full_name
		self.name + " " + self.last_name
	end

	def accordion
		"accordion" + self.id.to_s
	end

	def haccordion
		"#accordion" + self.id.to_s
	end

	def av_stars
		"av_stars" + self.id.to_s
	end

	def admin
		self.email == "jordi@jordi.com"
	end



end

app/models/venue.rb
class Venue < User
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 
  before_action :load_category, except: [:index, :new, :create]

  def index
  	@categories = Category.all.sort
  end

  def edit
  	@category = Category.find(params[:id])
  end

  def new
  	@category = Category.new
  end

  def update
  	if @category.update(category_params)
      # http://guides.rubyonrails.org/action_controller_overview.html#the-flash
      flash[:notice] = "category updated successfully"

      redirect_to category_path(@category)
    else
      flash[:error]  = "Ops! We couldn't update the category, please review the errors"
      render :edit
    end
  end

  def create
  	@category = Category.new(category_params)
  	if @category.save
  		redirect_to categories_url
  	else
  		render :new
  	end
  end

  def show
  	@category = Category.find(params[:id])
 		@categories = @category.subcategories
	end

  def destroy
  	@category = Category.find(params[:id])
  	@category.destroy
  	redirect_to categories_url
  end

  private

  def category_params
  	params.require(:category).permit(:name, :icon, :parent_id)
  end

  def load_category
    @category = Category.find(params[:id])
  end
  
end

app/controllers/login_controller.rb
# http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html
class LoginController < ApplicationController
  def create
    user = User.where(email: params[:email]).first
    # Session engaged
    if user && user.authenticate(params[:password])
      flash[:success] = "Login sucessful! Welcome #{user.name}!"

      session[:current_user_id] = user.id
    else
      flash[:error] = "Login was not sucessful"
    end

    redirect_to user_path(user.id)
  end

  def destroy
    session[:current_user_id] = nil

    respond_to do |format|
      format.html { redirect_to users_path }
      format.js   { render js: "window.location.href='#{users_path}'" }
    end
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |c| %>
		<% if @category.errors.any? %>
			<% @category.errors.full_messages.each do |message| %>
				<%= message %>
			<% end %>
		<% end %>
	<div class="container-fluid">
	<div class="form-group">
	<%= c.label :name %>
	<%= c.text_field :name, class: "form-control", placeholder: "Name of category " %>
	</div>
	<div class="form-group">
	<%= c.label :icon %>
	<%= c.text_field :icon, class: "form-control", placeholder: "icon url" %>
	</div>
	<div class="form-group">
	<%= c.label :parent_category %>
	<%= c.select :parent_id, options_for_select(Category.all.collect{ |c| [c.name, c.id]}), :include_blank => true %>
	</div>
	<div>
	<%= c.submit class: "btn btn-success"%>
	</div>
<% end %>


<div><%= link_to image_tag("backarrow.png"), categories_path, class: "backbutton" %></div>

app/views/categories/_form.html.haml
= form_for @category do |c|
  - if @category.errors.any?
    - @category.errors.full_messages.each do |message|
      = message
  .container-fluid
    .form-group
      = c.label :name
      = c.text_field :name, class: "form-control", placeholder: "Name of category "
    .form-group
      = c.label :icon
      = c.text_field :icon, class: "form-control", placeholder: "icon url"
    .form-group
      = c.label :parent_category
      = c.select :parent_id, options_for_select(Category.all.collect{ |c| [c.name, c.id]}), :include_blank => true
    %div
      = c.submit class: "btn btn-success"
    = link_to("Back", categories_path)

app/views/categories/_form.old.erb
<%= form_for @category do |c| %>
    <% if @category.errors.any? %>
      <% @category.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
  <div class="container-fluid">
  <div class="form-group">
    <%= c.label :name %>
    <%= c.text_field :name, class: "form-control", placeholder: "Name of category " %>
  </div>
  <div class="form-group">
  <%= c.label :icon %>
  <%= c.text_field :icon, class: "form-control", placeholder: "icon url" %>
  </div>
  <div class="form-group">
  <%= c.label :parent_category %>
  <%= c.select :parent_id, options_for_select(Category.all.collect{ |c| [c.name, c.id]}), :include_blank => true %>
  </div>
  <div>
  <%= c.submit class: "btn btn-success"%>
  </div>
<% end %>

<%= link_to("Back", categories_path) %>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h4>Edit Category</h4>

<%= render 'form'%>

app/views/categories/index.html.erb
<h4>Categories list</h4>
<table class="table table_stripted">
	<th>Category name</th>
	<th>Parent Category</th>
	<th>Parent Category</th>
	<th>Icon</th>
	<% @categories.each do |c| %> 
		<tr>
			<td><%= c.name %></td>
			<td><%= c.parent_name if c.parent_category %></td>
			<td>
			<%= if c.parent_category 
				 if c.parent_category.parent_category 
						 c.parent_category.parent_name
						  end
				 end %>	
			</td>	
			<td><%= c.icon %></td>
			<td><%= link_to "Edit", edit_category_path(c), :class => "btn btn-success" %>
			<%= link_to "Delete", category_path(c), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-success" %></td>	
		</tr>
	<% end %>
</table>
<div>
	<%= link_to "New category", new_category_path, id: "new_category", remote: true, :class => "btn btn-success" %>
</div>

app/views/categories/new.html.erb
<h4>New Category</h4>

<%= render 'form'%>

app/views/categories/new.js.erb
$('#new_category').hide().after('<%= j render("form") %>');

app/views/categories/show.html.erb
<h4>Show category <%= @category.name %></h4>


<table class="table table_stripted">
	<th>Subcategories</th>
	<th>Icon</th>
	

	<% @category.subcategories.each do |c| %>
		<tr>
			<td><%= c.name %></td>
			<td><%= c.icon %></td>
			<td><%= link_to "Edit", edit_category_path(c), :class => "btn btn-success" %><%= link_to "Delete", category_path(c), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-success" %></td>	
		</tr>
	<% end %>
</table>

<div>
	<%= link_to "New category", new_category_path, :class => "btn btn-success"%>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>