config/routes.rb
Rails.application.routes.draw do
   
  root 'users#index'
  
  get 'map' => 'users#map', as: :map

  get '/search/map' => 'searches#map', as: :search_map

  get 'teachers' => 'users#teachers'
  put 'teachers/:id' => 'users#update', as: :teacher
  patch 'teachers/:id' => 'users#update'

  get 'students' => 'users#students'
  put 'students/:id' => 'users#update', as: :student
  patch 'students/:id' => 'users#update'
  
  get 'venues' => 'users#venues'
  put 'venues/:id' => 'users#update', as: :venue
  patch 'venues/:id' => 'users#update'

  get 'show/:id' => 'users#show'
  get 'reviews_by/:id' =>'reviews#show_by', as: :reviews_by
  
  get 'searches' =>'searches#new'
  get 'searches/update_regions', to: 'searches#update_regions', :as => 'search_regions'
  get 'searches/update_cities', to: 'searches#update_cities', :as => 'search_cities'
  get 'users/update_regions', to: 'users#update_regions', :as => 'user_regions'
  get 'users/update_cities', to: 'users#update_cities', :as => 'user_cities'
  
  post 'search' => 'searches#create', as: :search_users

  resources :reviews
  resources :users, only: [:create, :index, :show, :edit, :update, :new, :destroy]
  resources :categories, only: [:create, :index, :show, :edit, :update, :new, :destroy]
  resources :searches, only: [:create, :new, :update]

  post 'reviews' => 'reviews#create'

 

  post   "/login",  to: "login#create"
  delete "/logout", to: "login#destroy"

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/cat_relation.rb
class CatRelation < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	validates_presence_of :user_id, :category_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories, :class_name => "Category", :foreign_key => "parent_id", :dependent => :destroy
  belongs_to :parent_category, :class_name => "Category", :foreign_key => "parent_id"
  has_many :courses
  has_and_belongs_to_many :users
  has_many :categories, through: :categories

  def parent_name
  	 if parent_category then parent_category.name else "" end
  end
  def <=> another
    if self.name < another.name
      -1
    elsif self.name < another.name
      1
    else
      0
    end
  end
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :region
 	belongs_to :country
 	has_many :users
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :regions
	has_many :cities
	has_many :users, class_name: "User", foreign_key: "user_id"
	def flag
		"flag-"+self.iso2.downcase
	end
end

app/models/course.rb
class Course < ActiveRecord::Base	
	belongs_to :category
	belongs_to :venue
	belongs_to :teacher
	has_many :students
	has_many :reviews
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/region.rb
class Region < ActiveRecord::Base
	belongs_to :country
	has_many :cities
 	has_many :users
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :author, class_name: "User", foreign_key: "author_id"
	belongs_to :reviewed, class_name: "User", foreign_key: "reviewed_id"
	belongs_to :course
	validates_presence_of :rating, :author_id
	validates :rating, :inclusion => 0..5
end

app/models/search.rb
class Search < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :categories
end

app/models/student.rb
class Student < User
end

app/models/teacher.rb
class Teacher < User
end

app/models/user.rb
class User < ActiveRecord::Base

	mount_uploader :picture, UserPictureUploader
	TYPES = ["Teacher","Venue","Student"]
	has_secure_password

	has_many :reviews
	has_many :reviews_by, class_name: "Review", foreign_key: "author_id"
	has_many :reviews_to, class_name: "Review", foreign_key: "reviewed_id"
	has_many :courses, class_name: "Course", foreign_key: "courses_id"
	belongs_to :city
	belongs_to :region
	belongs_to :country

	validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i } 
	validates_length_of :short_description, :maximum => 80
	has_and_belongs_to_many :categories

	geocoded_by :full_street_address   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates
	
	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode  # auto-fetch address

	def full_street_address
		city = (self.city) ? self.city.name : ""
		region = (self.region) ? self.region.name : ""
		country = (self.country) ? self.country.name : ""
  	[address, town, city, region, country].compact.join(', ')
	end

	scope :located, -> { where.not(latitude: nil).where.not(longitude: nil) }
	
	def average_rating
		if self.reviews_to.count > 0
  	(self.reviews_to.sum(:rating).to_f / self.reviews_to.size.to_f).round(2)
	  else
	  	0
	  end
	end

	def url
		("users/"+ self.id.to_s)
	end

	def full_name
		self.name + " " + self.last_name
	end

	def accordion
		"accordion" + self.id.to_s
	end

	def haccordion
		"#accordion" + self.id.to_s
	end

	def av_stars
		"av_stars" + self.id.to_s
	end

	def admin
		self.email == "jordi@jordi.com"
	end



end

app/models/venue.rb
class Venue < User
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomadets</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <script src="http://code.jquery.com/jquery.min.js"></script>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">	
	<link href='http://fonts.googleapis.com/css?family=Gochi+Hand' rel='stylesheet' type='text/css'>	
</head>

<body>	
<!-- 		<div class="page-header">
		 	<img src="/assets/nomadets_logo.jpg" id="logo" class="logo">
-->
  <div class="container-fluid">
		<% flash.map do |key, msg| %>
	    <%= content_tag :div, msg, id: key %>
	  <% end %>
  <div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
	  <nav class="navbar navbar-default" role="navigation">
	    <ul class="nav navbar-nav navbar-collapse" id="menu_borde">
	  		<li class="logo-text"><%= link_to "", root_path %></li>
				<li><%= link_to "Teachers", teachers_path %></li>
				<li><%= link_to "Venues", venues_path %></li>
				<li><%= link_to "Students", students_path %></li>
				<% if admin %>
					<li><%= link_to "Categories", categories_path %></li>
				<% end %>
				<li><%= link_to "Search", searches_path %></li>
				<% if current_user %>
					<li><%= link_to "Reviews", reviews_by_path(current_user.id) %></li>
					<li><%= link_to "Profile", user_path(current_user.id) %></li>
					<li><%= link_to "Settings", edit_user_path(current_user.id) %></li>
				<%end%>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="login">
	  			<% if current_user %>		
						<%= render "users/logout_form" %>					
						<% else %>						
						<%= render "users/login_form" %>									
					<% end %>
				</li>
				<% if !current_user %>
					<li class="login">	
					<%= link_to 'Sign Up', new_user_path %>	
					</li>
				<%end%>
			</ul>
		</nav>
		</div>
	</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-body">

			<%= yield %>
			
		</div>	
		<div class="panel-footer navbar-fixed-bottom">		
			<h6>Copyright Nomadets 2015 </h6>
	</div>	
	</div>

</body>
</html>